services:

  db:
    container_name: db-chat-ia
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

  chat-ia:
    container_name: chat-ia
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: 
      - .env
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DB_NAME: chat
      DB_USER: admin
      DB_PASSWORD: admin
      DB_HOST: db
      DB_PORT: 5432

volumes:
  postgres_data: {}
