# Generated by Django 5.1.3 on 2024-11-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_chatbot_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='message_title',
            field=models.TextField(null=True),
        ),
    ]
